name: ML Workspace Infrastructure - $(date:yyyyMMdd)


trigger:
  - main

parameters:
  - name: buildMLWorkspace
    type: boolean
    default: false

variables:
  - group: terraform-backend-config

stages:
- stage: BuildInfra
  condition: ${{ parameters.buildMLWorkspace }}
  jobs:
  - job: BuildInfrastructure
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: 'IaC'

    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        # command: 'init'
        backendType: 'azurerm'
        backendServiceArm: 'ado_ml'
        backendAzureRmResourceGroupName: '$(backend_resource_group_name)'
        backendAzureRmStorageAccountName: '$(backend_storage_account_name)'
        backendAzureRmContainerName: '$(backend_container_name)'
        backendAzureRmKey: '$(backend_key)'
        workingDirectory: 'IaC'

    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: 'IaC'
        environmentServiceName: 'ado_ml'
        
    - task: ManualValidation@0
      inputs:
        instructions: 'Please manually validate the Terraform plan before applying.'
        timeoutInMinutes: 120
        
    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: 'IaC'
        environmentServiceName: 'ado_ml'
